### ISSUE TITLE
Add CUDA 11.6 packages.

### ISSUE THREAD

**Issue by bdice** [rapidsai/ptxcompiler#13]
I'd like to request CUDA 11.6 conda packages when possible.

The missing `ptxcompiler` packages for CUDA 11.6 are the only blocker for me to use CUDA 11.6 with [rapids-compose](https://github.com/trxcllnt/rapids-compose). I currently have a workaround of removing the [`ptxcompiler` dependency from the cuDF conda environment](https://github.com/rapidsai/cudf/blob/cfb6cbe6a8e4b01d7ee28fbe3212b5f2eb275167/conda/environments/cudf_dev_cuda11.5.yml#L70).

**Comment by quasiben** [comment]
I have a test build on my channel can you give it a try ? (currently py 3.8)

> conda install -c quasiben ptxcompiler

**Comment by bdice** [comment]
@quasiben I confirm that this package can be installed. Can you produce variants for Python 3.7 - 3.9? (Or maybe even 3.10 if we don't expect this package to change much over time.)

**Comment by quasiben** [comment]
Yeah, I'll get those built shortly.  Can I ask you to test/confirm things generally work with 11.6 ?  This could be done by running the entire test suite or, more importantly, test which flex UDFs:
- test_cuda_apply.py
- test_applymap.py
- test_apply_rows.py
- test_groupby.py

**Comment by quasiben** [comment]
@bdice all packages are now uploaded: py37, py39, py39, py310

**Comment by bdice** [comment]
The build for Python 3.9 `py39h107f55c_0` also works for me. I ran the tests and they appear to work fine. Can these packages be moved to the `rapidsai` channel?

**Comment by gmarkall** [comment]
cc @jakirkham for visibility

**Comment by quasiben** [comment]
This has now been resolved.  All packages built and are uploaded to rapidsai and rapidsai-nightly
