### ISSUE TITLE
Request: update for CUDA 11.7

### ISSUE THREAD

**Issue by wbthomason** [rapidsai/ptxcompiler#18]
Hi! I'd like to request that this package be updated to install with CUDA 11.7. Currently, this dependency requirement blocks `cuDF` from installing on my system. Would it be possible to increase this package's bound for `__cuda`?

**Comment by bdice** [comment]
Hi @wbthomason! We’re working on this. It takes a bit of time after a new CUDA release to update the full ecosystem (Docker images, dependency tree of conda packages, etc.) but this should be fixed soon. I’ll follow up!

See also: https://github.com/rapidsai/ptxcompiler/issues/19#issuecomment-1133632304 and previous issue #13 for 11.6.

cc: @shwina @quasiben @gmarkall

**Comment by bdice** [comment]
@wbthomason This should now be resolved with the new ptxcompiler package for CUDA 11.7. In https://github.com/conda-forge/ptxcompiler-feedstock/pull/10, the upper bound on `__cuda` was removed (we think it's no longer needed).

Please let us know if you have any further issues!

**Comment by gmarkall** [comment]
Closing as this appears to be resolved and no further feedback has been received.
