### ISSUE TITLE
Rapids fails to install using mamba

### ISSUE THREAD

**Issue by MordicusEtCubitus** [rapidsai/ptxcompiler#19]
Dears,

I've tried to install rapids using mamba in place of conda and got this error:

```bash
bash$ mamba create -n rapids-mamba -c rapidsai -c nvidia -c conda-forge rapids=22.04 python=3.9 cudatoolkit=11.2 dask-sql
Encountered problems while solving.
Problem: package rapids-22.04.00-cuda11_py39_ge08d166_149 requires ptxcompiler, but none of the providers can be installed
```

If I try to install ptxcompiler only using mamba I got this issue:
```bash
bash$ mamba install -c rapidsai -c nvidia -c conda-forge ptxcompiler
Problem: package ptxcompiler-0.2.0-py39h114ffae_0 has constraint __cuda >=11.0,<=11.5 conflicting with __cuda-11.7-0
```

I have installed cuda-11-2 only, so I'm surprised but my nvidia-smi show conda 11.7 in the header... 

There is no issue if I use conda, so it may be a mamba issue.

But regarding defect 13 https://github.com/rapidsai/ptxcompiler/issues/13 maybe it is a version mismatch...

So I prefer to get your point before cross posting

Thanks in advance

**Comment by shwina** [comment]
Thanks for reporting @MordicusEtCubitus . We're aware and working on resolving this issue with the ptxcompiler package. We'll post an update here when a version of  ptxcompiler that works with 11.7 drivers is available.

cc: @bdice

**Comment by bdice** [comment]
@MordicusEtCubitus This should now be resolved with the new ptxcompiler package for CUDA 11.7. In https://github.com/conda-forge/ptxcompiler-feedstock/pull/10, the upper bound on `__cuda` was removed (we think it's no longer needed).

Please let us know if you have any further issues!

**Comment by gmarkall** [comment]
Closing as this appears to be resolved and no further feedback was received.
